### ISSUE TITLE
[BUG] Hiding macOS app minimizes window to dock, should hide instead

### ISSUE THREAD

**Issue by jenskasemets** [tact/public#101]
## Describe the bug

When hiding macOS app, it should hide all the app's windows. Tact, instead of hiding,  minimizes window to dock

## Environment

 - Tact version 1.2 (152)
 - Hardware: MBA
 - OS version: 12.0.1 Big Sur

## To reproduce

1. Open Tact app
2. Check that Tact app is foremost and it has at least one window open
3. Select "Hide Tact" from "Tact" on the menubar / or press mac+H

## Expected behavior

Tact app should be hidden, as default behaviour is on macOS for all the apps

## Observed behavior

Tact app is not hidden, but app is put on background and Tact app window is minimised to Dock

**Comment by jaanus** [comment]
Was recently fixed.
