### ISSUE TITLE
[BUG] Messages only show for a split second when selecting a chat from the list

### ISSUE THREAD

**Issue by siimpragi** [tact/public#102]
## Describe the bug

I created a new group chat and tried to switch to it but couldn't. I couldn't switch to the single DM chat that was already there before either. When clicking on a chat in the left-side menu its messages were only flashed for a split second. Couldn't get past the "Select a chat in the list to show recent messages." screen. Please see the first recording below.

Doing "Clear Local Data & Restart Tact" didn't help. What did help, however, was sending a message request to someone.

I tried to reproduce this behavior. It seems to happen when deleting a group chat from the list (second recording). It happened in case of a regular chat as well (third recording). Can't tell for sure when and why, though.

## Environment

 - Tact version 1.2 (152)
 - Hardware: MacBook Air (M1, 2020)
 - OS version: Big Sur **11.6** (20G165)

## Screen recordings

https://user-images.githubusercontent.com/8535926/146967887-bfe23803-31b0-460f-beb8-306590e0ec90.mov

https://user-images.githubusercontent.com/8535926/146970256-84680ec5-1f59-46cc-bdbf-f6399e295306.mov

https://user-images.githubusercontent.com/8535926/146971496-66c7b5b6-effe-4019-9b58-db0eac1ac905.mov

**Comment by siimpragi** [comment]
I should probably add that I haven't noticed anything like this since upgrading to Monterey. 😄 Good to close, imo.

**Comment by jaanus** [comment]
Yep, haven’t seen similar recent reports, closing.
