### ISSUE TITLE
Button's text hard to read if dark mode enabled

### ISSUE THREAD

**Issue by siimpragi** [tact/public#106]
This is a bit nit-picky perhaps, but if you have dark mode enabled and tap on the three dots menu icon: the text on one of the buttons is quite difficult to read.

| iOS 14.8 | macOS 12.1 |
|-----------|-----------|
| <img width="200" src="https://user-images.githubusercontent.com/8535926/147149289-50aba2a2-96e7-4dca-8adf-c130451e3fef.png"> | <img width="300" src="https://user-images.githubusercontent.com/8535926/147149312-5c89fcd7-6094-45c1-a5c0-e3f7f9718e10.png"> |

Both have Tact version 1.2 (153).

**Comment by jaanus** [comment]
Not nitpicky at all, thank you for posting. This is a real bug, all buttons should be readable in all modes, will fix.

**Comment by jaanus** [comment]
Also reported on iOS in another view by a tester on TestFlight.

![original](https://user-images.githubusercontent.com/184253/147357556-02865004-86d5-47dd-894d-daa782a94546.jpg)

**Comment by jaanus** [comment]
Fixed in 1.2 (154).
