### ISSUE TITLE
[BUG] Double messages, reactions, and joins

### ISSUE THREAD

**Issue by mattahorton** [tact/public#110]
## Describe the bug

A short description of what the bug is.

## Environment

 - Tact version 1.2 (159)
 - Hardware: iPhone14,2
 - OS version: iOS 15.3 (19D50)

## To reproduce

Unsure, but what I did was install from Testflight, join a group chat I was invited to, and view earlier messages.

## Expected behavior

I expected to join an existing group chat and see single instances of messages, reactions, and chat joins in the chat history.

## Observed behavior

Dual copies of messages, reactions, and chat joins when joining the Everyone chat after installing from testflight.

## Screenshots, logs, etc

<img width="472" alt="Screen Shot 2022-02-14 at 12 26 50 PM" src="https://user-images.githubusercontent.com/5567285/153924185-e51c9e1e-00b1-4d14-a5f9-0a07095f169c.png">

## Any other info

I shared a video of the problem with jaanus via Tact as well. I was unable to upload that video here.

Also, I uninstalled the app and reinstalled via Testflight (at Jaanus' request) and the bug is no longer present.

**Comment by jaanus** [comment]
Fixed in 1.2 (161). Should not happen any more.
