### ISSUE TITLE
MacOS Crash

### ISSUE THREAD

**Issue by joonathan** [tact/public#112]
## Describe the bug

Tact had crashed in the background.

## Environment

 - Tact version Version 1.2 (162)
 - Hardware: MacBook Pro 16
 - OS version: MacOs 12.3 (21E230)

## Any other info

[2022-03-28T10-16-24Z.plcrash.zip](https://github.com/tact/public/files/8361843/2022-03-28T10-16-24Z.plcrash.zip)

**Comment by jaanus** [comment]
Checked log, same as #114, closing this one as older duplicate.
