### ISSUE TITLE
Crashes around marking messages as read/unread

### ISSUE THREAD

**Issue by jaanus** [tact/public#114]
Reported by @joonathan, a few crashes.

[crashes.zip](https://github.com/tact/public/files/8554571/crashes.zip)

**Comment by joonathan** [comment]
[2022-05-17T07-24-36Z.plcrash.zip](https://github.com/tact/public/files/8706097/2022-05-17T07-24-36Z.plcrash.zip)

**Comment by jaanus** [comment]
[Crashes with symbols.zip](https://github.com/tact/public/files/8728047/Crashes.with.symbols.zip)

Here are the logs with correct symbols.

I hope I got it fixed. Or if not, I have a good idea where to look next.

Closing this for now. If happens again, open a new issue with logs.
