### ISSUE TITLE
[BUG] Invitation to chat results in "Unknown error" sheet

### ISSUE THREAD

**Issue by jmaaloe** [tact/public#118]
## Describe the bug

Attempting to invite user to a conversation via their shared link (from a webview in the Twitter app) let me type out the initial message but resulted in the invite screen displaying sheet saying "unknown error" instead of sending the message.

## Environment

Tact version 1.3.0 (258)
Hardware: iPhone 13 Pro
iOS Version 16.0 (Build 20A362)

_You can get these details in Settings, About._

## To reproduce

1. Go to https://jaanus.com/tact-app-store/
2. Tap on "myself" link on page
3. Tap on "I have Tact"
4. Write message and tap send

## Observed behavior

What you actually saw (what is the bug).

## Screenshots, logs, etc

If applicable, add screenshots, logs, screen recording, or any other material to help explain your problem.

<img src="https://user-images.githubusercontent.com/2072298/204521336-088bbb9a-61e7-4696-a532-70d591f10199.PNG" width=320 />

<img src="https://user-images.githubusercontent.com/2072298/204521344-43d90f34-d998-43a5-a591-239638fbf9c1.PNG" width=320 />

## Any other info

This was my first launch of the app, and first initiated conversation

**Comment by jaanus** [comment]
Thank you for the report. Obviously a problem, I’ll need to look into it and fix it.

If anyone else is encountering this, there are two workarounds until this is fixed.

1. If opening the chat fails in one direction, share the other person’s link and start the chat in the other direction.
2. If you happen to be physically close to the other person, start the chat with Nearby.

**Comment by jaanus** [comment]
There indeed is an error that happens if you try to open someone’s invitation link immediately after installing up and setting your name and picture. I have found the error and fix will be in the next version. Current workaround is to kill and restart the app. Some things are not set up correctly when creating your first user  in the first run of the app 🤦

**Comment by jaanus** [comment]
Fixed in 1.3.2 (269), released to App Store a few days ago.
