### ISSUE TITLE
Do not show notifications when Mac app is closed

### ISSUE THREAD

**Issue by jenskasemets** [tact/public#97]
## Describe the bug

Do not show notifications when app is closed

## Environment

 - Tact version  1.2 (150
 - Hardware: Mac
 - OS version: Big Sur 12.0.1

## To reproduce

1. Quit Tact app
2. Receive a new message
3. Notification for the new message is shown in the notification center

## Expected behavior

Notification should not be shown in the case app is not running

**Comment by jaanus** [comment]
Fixed in 1.2 (165).
